In [8]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

df=pd.read_csv('/content/drive/MyDrive/Irwin data analysis portfolio/data/data/celebrity_deaths_2016.csv',
                usecols=['dateofdeath','age'])

df['month']=df['dateofdeath'].str.slice(5,7)

df=df.set_index('month').sort_index()

df=df.dropna(subset=['age'])

#df=df[df['age'].str.isdigit()]# one way of doing it by selecting and removing rows within the age column with non numerical values

df['age']=pd.to_numeric(df['age'], errors='coerce')# another way of doing it by creating a new age column turning the values into integer or float and  precise to ignore any errors

df=df.loc[df['age']<120]

df.loc['02':'07', 'age'].mean().round()#Find the average age of celebrities who died from February to July 2016

77.0