In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
df=pd.read_csv('/content/drive/MyDrive/Irwin data analysis portfolio/data/data/linux-etc-passwd.txt',
               sep=':',
               comment='#',
               header=None,
               skip_blank_lines=False,
               names=['username','password', 'userid','groupid', 'name', 'homedir', 'shell'],
               usecols=['username', 'userid', 'groupid', 'name', 'homedir', 'shell'] )
df=df.loc[df['userid']>1000]
df['username']

21    nobody
28    reuven
37    genadi
38     shira
39     atara
40    shikma
41     amotz
48       git
51    deploy
Name: username, dtype: object