In [ ]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

df=pd.read_csv('/content/drive/MyDrive/Irwin data analysis portfolio/data/data/olympic_athlete_events.csv',
               usecols=['Age', 'Height','Team','Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
               index_col=['Year','Season','Sport','Event'])# by passing a list of columns to the index_col parameter, we create a multi-index while creating the data frame rather than doing it in a separate second step
df=df.sort_index()# then, we use sort_index, which returns a new data frame containing the same data with the rows ordered according to the multi-index

df.loc[(slice(1936,2000),'Summer'), 'Age'].mean().round(4)# what is the average age of winning athletes in summer games held between 1936 and 2000

df.dropna(subset='Medal').loc[(slice(None),slice(None),'Archery',), 'Team'].value_counts()# what team has won the most medals in all archery events

df.loc[((slice(1980, None),slice(None),slice(None),"Table Tennis Women's Team")), 'Height'].mean()# starting in 1980 , what is the average height of the "table tennis women's event"

df.loc[(slice(1980, None), slice(None), slice(None),["Table Tennis Men's Team","Table Tennis Women's Team"]), 'Height'].mean()# starting in 1980 , what is the average height of both "Table Tennis Women's Team" and "Table Tennis Men's Team" ?

df.loc[(slice(1980, 2016), slice(None), 'Tennis'), 'Height'].max()# How tall was the tallest-ever tennis player in Olympic games from 1980 until 2016?

208.0